services:
  workoutwise.api:
    image: workoutwise-api:latest
    build:
      context: .
      dockerfile: src/WorkoutWise.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    

  workoutwise.database:
    image: postgres:latest
    container_name: workoutwise.database
    environment:
        POSTGRES_DB: workoutwisedb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
        - 5432:5432