services:
  workoutwise.api:
    image: ${DOCKER_REGISTRY-}workoutwiseapi
    build:
      context: .
      dockerfile: src/WorkoutWise.API/Dockerfile

  workoutwise.database:
    image: postgres:latest
    container_name: workoutwise.database
    environment:
        POSTGRES_DB: workoutwisedb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
        - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
        - 5432:5432